-- Create Two Tables
CREATE TABLE players (
  PLAYER_NAME TEXT PRIMARY KEY,
  TEAM_NAME TEXT,
  PLAYER_SALARY VARCHAR(30)
);

CREATE TABLE teams (
  TEAM_NAME TEXT PRIMARY KEY,
  TEAM_WORTH VARCHAR(30)
);
