-- Create Two Tables
CREATE TABLE nbaplayers (
  PLAYER_NAME TEXT PRIMARY KEY,
  TEAM_NAME TEXT,
  PLAYER_SALARY VARCHAR(30)
);

CREATE TABLE nbateams (
  TEAM_NAME TEXT PRIMARY KEY,
  TEAM_WORTH VARCHAR(30)
);
